services:
  postapp1:
    image: postservice2
    #container_name: postmessage
    ports:
      - "8090:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/mydatabase
    restart: 'on-failure'
    volumes:
      - mongodb:/data/db

  postapp2:
    image: postservice2
    container_name: postmessage2
    ports:
      - "8091:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/mydatabase
    restart: 'on-failure'
    volumes:
      - mongodb:/data/db

  mongodb:
    image: 'mongo:latest'
    ports:
      - '27017:27017'

    volumes:
      - mongodb:/data/db

volumes:
  mongodb:



#services:
#  mongodb:
#    image: 'mongo:latest'
#    environment:
#      - 'MONGO_INITDB_DATABASE=mydatabase'
#      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
#      - 'MONGO_INITDB_ROOT_USERNAME=root'
#    ports:
#      - '27017:27017'
#  rabbitmq:
#    image: 'rabbitmq:latest'
#    environment:
#      - 'RABBITMQ_DEFAULT_PASS=secret'
#      - 'RABBITMQ_DEFAULT_USER=myuser'
#    ports:
#      - '5672'
