services:
  postapp1:
    image: postservice2
    container_name: postmessage
    ports:
      - "8090:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/mydatabase
    restart: 'on-failure'
    networks:
        - mynetwork
    volumes:
      - mongodb:/data/db

  postapp2:
    image: postservice2
    container_name: postmessage2
    ports:
      - "8091:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/mydatabase
    restart: 'on-failure'
    networks:
        - mynetwork


    volumes:
      - mongodb:/data/db


  mongodb:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    networks:
      - mynetwork

    volumes:
      - mongodb:/data/db

networks:
  mynetwork: {}
volumes:
  mongodb:
